spacebook/posts/urls.py
from django.urls import path
from posts.models import Post
from posts import views
app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),
    path("by/<username>/<int:pk>/",views.PostDetail.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
]

spacebook/spacebook/urls.py
from django.contrib import admin
from django.urls import path,include
from spacebook import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('groups/',include('groups.urls',namespace='groups')),
    path('posts/',include('posts.urls',namespace='posts')),
]

spacebook/posts/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth import get_user_model
from groups.models import Group
# Create your models here.
User = get_user_model()
import misaka

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    message = models.CharField(max_length=512,blank=False)
    created_at = models.DateTimeField(auto_now=True)
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='posts',null=True,blank=True)

    def __str__(self):
        return self.message

    def save(self,*args,**kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('posts:single',kwargs={'username':self.user.username,'pk':self.pk})

    class Meta():
        ordering = ['-created_at']
        unique_together = ['user','message']

spacebook/posts/views.py
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import Http404
from django.views import generic

from braces.views import SelectRelatedMixin
# Create your views here.
from posts import models
from posts import forms

from django.contrib.auth import get_user_model

User = get_user_model()

class PostList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ("user", "group")


class UserPosts(LoginRequiredMixin,generic.ListView):
    model = models.Post
    template_name = "posts/user_post_list.html"

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related("posts").get(
                username__iexact=self.kwargs.get("username")
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_user"] = self.post_user
        return context

class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ("user", "group")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            user__username__iexact=self.kwargs.get("username")
        )


class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    # form_class = forms.PostForm
    fields = ('message','group')
    model = models.Post

    # def get_form_kwargs(self):
    #     kwargs = super().get_form_kwargs()
    #     kwargs.update({"user": self.request.user})
    #     return kwargs

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ("user", "group")
    success_url = reverse_lazy("posts:all")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Post Deleted successfully")
        return super().delete(*args, **kwargs)

spacebook/templates/posts/_post_.html
<div class="card postcard">
  <h4 class="text-center card-header">
     <a href="{% url 'posts:for_user' username=post.user.username %}">@{{post.user.username}}</a>
   </h4><div class="card-body">
     <p class="text-center">{{post.message_html|safe}}</p>
   </div>
   <div class="card-footer">
     <time class="time">Posted on {{ post.created_at }}</time>
     {% if post.group %}
     <span class="group-name">in <a href="{% url 'groups:single' slug=post.group.slug %}">{{ post.group.name }}</a></span>
     {% endif %}
   </div>
   <div class="card-footer ml-auto">
   {% if user.is_authenticated and post.user == user and not hide_delete %}
     <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-outline-danger btn-sm">
       <span class="fa fa-remove text-danger" aria-hidden="true"></span>
       <span class="text icon-label" id="delete35">Delete</span>
     </a>
   {% endif %}
 </div>
</div>

spacebook/templates/posts/post_base.html
{% extends "base.html" %}
{% block content %}
<div class="posts_page">
  <div class="container">
    <div class="row">
        {% block prepost %}
        {% endblock %}

        {% block post_cont %}
        {% endblock %}

        {% block postpost %}
        {% endblock %}
    </div>
  </div>
</div>
{% endblock %}

spacebook/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}

{% block post_cont %}
<h3>Are you sure you want to delete this post?</h3>

<div class="posts">
	{% include "posts/_post_.html" with post=object hide_delete=True %}
</div>

<form method="POST">
	{% csrf_token %}
	<input type="submit" value="Confirm Delete" class="btn btn-danger btn-lg mr-5">
	<a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn btn-light btn-lg">Cancel</a>
</form>

{% endblock %}

spacebook/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}
{% block prepost %}
  <div class="col-md-6">
    {% include "posts/_post_.html" %}
  </div>
{% endblock %}

spacebook/templates/posts/post_form.html
{% extends "posts/post_base.html" %}
{% load bootstrap4 %}
{% block post_cont %}
  <div class="container">
    <h3 class="display-4 text-center">New Post</h3>
    <p class="col-md-10 title2 text-right">Share your views with us.</p>
    <form class="form thumbs" action="{% url 'posts:create' %}" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-outline-light btn-lg mr-2"value="Post">
      <input type="reset" value="Cancel" class="btn btn-outline-warning btn-lg ml-auto">
    </form>
  </div>
{% endblock %}

spacebook/templates/posts/post_list.html
{% extends "posts/post_base.html" %}
{# {% load humanize %} #}
{% block prepost %}
<div class="container">
  <div class="col-md-4">
    {% if user.is_authenticated %}
      <div class="card">
        <h4 class="card-header">Your Groups</h4>
      </div>
      <div class="card-body">
        <ul class="list-group">

          {% for member_group in get_user_groups %}
          <li class="list-group-item">
            <a href="{% url 'groups:single' slug=member_group.group.slug %}">{{ member_group.group.name }}</a>
          </li>
          {% endfor %}

        </ul>
      </div>
    {% endif %}
    <div class="card">
      <div class="content">
        <h5 class="card-title">All groups</h5>
        <ul class="list-group">
          {# {% get_other_groups as other_groups %} #}
          {% for other_group in get_other_groups %}
            <li class="list-group-item"><a href="{% url 'groups:single' slug=other_group.slug %}">{{ other_group.name }}</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block post_cont %}
<br><br>
  <div class="col-md-8">
  	{% for post in post_list %}
    {% include "posts/_post_.html" %}
  	{% endfor %}
  </div>
{% endblock %}

spacebook/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}
{% block prepost %}
  <h3 class="display-3 col-md-4">@{{post_user.username}}</h3>
{% endblock %}
{% block post_cont %}
  <div class="col-md-8">
    {% for post in post_list %}
      {% include "posts/_post_.html" %}
    {% endfor %}
  </div>
{% endblock %}