spacebook/groups/urls.py
from django.urls import path
from groups.models import Group,GroupMember
from groups.views import CreateGroup,ListGroup,SingleGroup,JoinGroup,LeaveGroup
app_name = 'groups'

urlpatterns = [
    path('create/',CreateGroup.as_view(),name='create'),
    path('',ListGroup.as_view(),name='all'),
    path('posts/in/<slug>/',SingleGroup.as_view(),name='single'),
    path("join/<slug>/",JoinGroup.as_view(),name="join"),
    path("leave/<slug>/",LeaveGroup.as_view(),name="leave"),
]

spacebook/posts/urls.py
from django.urls import path
from posts.models import Post
from posts import views
app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),
    path("by/<username>/<int:pk>/",views.PostDetail.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
]

spacebook/spacebook/urls.py
from django.contrib import admin
from django.urls import path,include
from spacebook import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('groups/',include('groups.urls',namespace='groups')),
    path('posts/',include('posts.urls',namespace='posts')),
]

spacebook/groups/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse,reverse_lazy
# Create your models here.
import misaka
from django.contrib.auth import get_user_model
from django import template
from django.contrib.auth.models import User
register = template.Library()

class Group(models.Model):
    name = models.CharField(max_length=64,unique=True)
    slug = models.SlugField(max_length=64,allow_unicode=True,unique=True)
    desc = models.TextField(max_length=256,blank=True,default='')
    desc_html = models.TextField(blank=True,default='',editable=False)
    members = models.ManyToManyField(User,through='GroupMember')

    def __str__(self):
        return self.name
    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        self.desc_html = misaka.html(self.desc)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('groups:single',kwargs={'slug':self.slug})

    class Meta():
        ordering = ['name']

class GroupMember(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE,related_name='memberships')
    user = models.ForeignKey(User, on_delete=models.CASCADE,related_name='user_groups')

    def __str__(self):
        return self.user.username

    class Meta():
        unique_together = ('group','user')

spacebook/groups/views.py
from django.shortcuts import render
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.mixins import PermissionRequiredMixin,LoginRequiredMixin
from groups.models import Group, GroupMember
from django.views.generic import CreateView,DetailView,ListView,DeleteView,RedirectView
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from groups import models
# Create your views here.

class CreateGroup(CreateView,LoginRequiredMixin):
    fields = ['name','desc']
    model = Group

class SingleGroup(DetailView,LoginRequiredMixin):
    model = Group
    template_name = 'groups/group_detail.html'

class ListGroup(ListView,LoginRequiredMixin):
    model = Group
    template_name = 'groups/group_list.html'

class JoinGroup(LoginRequiredMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get("slug"))

        try:
            GroupMember.objects.create(user=self.request.user,group=group)

        except IntegrityError:
            messages.warning(self.request,("Warning, already a member of {}".format(group.name)))

        else:
            messages.success(self.request,"You are now a member of the {} group.".format(group.name))

        return super().get(request, *args, **kwargs)


class LeaveGroup(LoginRequiredMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        try:
            membership = models.GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get("slug")
            ).get()

        except models.GroupMember.DoesNotExist:
            messages.warning(
                self.request,
                "You can't leave this group because you aren't in it."
            )

        else:
            membership.delete()
            messages.success(
                self.request,
                "You have successfully left this group."
            )
        return super().get(request, *args, **kwargs)

spacebook/templates/groups/group_base.html
{% extends "base.html" %}
{% block content %}

<div class="container">
  <div class="row">
    {% block pregroup %}
    {% endblock %}
    {% block group_cont %}
    {% endblock %}
    {% block postgroup %}
    {% endblock %}
  </div>
</div>

{% endblock %}

spacebook/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
  <div class="container">
    <h4>{{group.name}}</h4>
    <p class="text-info">Members count: {{group.members.count}}</p>
    {% if user in group.members.all %}
      <a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-outline-secondary btn-lg">Leave Group</a>
    {% else %}
      <a href="{% url 'groups:join' slug=group.slug %} " class="btn btn-outline-primary btn-lg">Join Group</a>
    {% endif %}
  </div>
{% endblock %}

{% block group_cont %}
  <div class="col-md-8">
    {% if group.post.count == 0 %}
      <h3>No posts in this group yet!</h3>
    {% else %}
      {% for post in group.posts.all %}
        {% include "posts/_post_.html" %}
      {% endfor %}
    {% endif %}
  </div>
{% endblock %}

spacebook/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap4 %}

{% block pregroup %}
<div class="container">
    <br> <h4 class="display-4 text-center">Create your own Group now</h4><br><br><br>
</div>
{% endblock %}

{% block group_cont %}
  <form class="form thumbs" action="{% url 'groups:create' %}" method="post" id="groupform">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-success btn-lg" value="Create">
    <input type="reset" class="btn btn-danger btn-lg" value="Clear">
  </form>
{% endblock %}

spacebook/templates/groups/group_list.html
{% extends "groups/group_base.html" %}
{% block pregroup %}
  <div class="container">
    <div class="col-md-4">
      {% if user.is_authenticated %}
        <h3>Welcome Back
        <a href="{% url 'posts:for_user' username=user.username %}">@{{user.username}}</a>
        </h3>
      {% else %}
        <h3>Welcome to the Groups Page</h3>
        <p class="text-secondary">Pick a group to join and do shit together.</p>
      {% endif %}
    </div><br><hr>
    {% if user.is_authenticated %}
      <a class="btn btn-outline-success btn-md" href="{% url 'groups:create' %}">Create New Group</a>
    {% endif %}
  </div>


{% endblock %}

{% block group_cont %}
  <div class="container">
    <div class="col-md-8">
      <div class="list-group">
        <br>
        {% for group in object_list %}
          <div class="postcard">
            <div class="list-item">
              <a href="{% url 'groups:single' slug=group.slug %}"> <h3>{{group.name}}</h3>
              </a>
              <div class="list-item-text container-fluid">
                {{group.desc_html|safe}}
                <div class="row">
                  <div class="col-md-4">
                    <span class="badge">{{group.members.count}}</span>
                    member{{group.members.count|pluralize}}
                  </div>
                  <div class="col-md-4">
                    <span class="badge">{{group.posts.count}}</span>
                    post{{group.posts.count|pluralize}}
                  </div>
                </div>
              </div>
              <hr>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>

{% endblock %}